---

# add repo
- name: Install epel repo
  yum:
    name: "{{ epelCentosUrl }}"
    state: "{{ epelCentosState }}"

# add the epel rpm key
- name: add rpm key
  rpm_key:
    key: "{{ epelCentosRpmKey }}"
    state: "{{ epelCentosState }}"

# enable/disable the correct repo's
- name: configure repo's
  command: "yum-config-manager --{{ item.state | default('disable') }} {{ item.name }}"
  register: yumConfigStatus
  changed_when: yumConfigStatus.rc == 2
  with_items:
    - "{{ epelCentosRepoList }}"
