---

- name: Epel | RedHat | Install required tools
  yum:
    name: "yum-utils"
    state: "installed"

# add the epel rpm key
- name: Epel | RedHat | add rpm key
  rpm_key:
    key: "{{ epelCentosRpmKey }}"
    state: "{{ epelCentosState }}"

# add repo
- name: Epel | RedHat | Install epel repo
  yum:
    name: "{{ epelCentosUrl }}"
    state: "{{ epelCentosState }}"

# enable/disable the correct repo's
- name: Epel | RedHat | configure repo's
  command: "yum-config-manager --{{ item.state | default('disable') }} {{ item.name }}"
  register: yumConfigStatus
  changed_when: yumConfigStatus.rc == 2
  with_items:
    - "{{ epelCentosRepoList }}"
